### ISSUE TITLE
Destination path only home directory?

### ISSUE THREAD

**Issue by david-e-rupp** [palexandremello/goes-py#7]
First, thanks for this handy tool!

Second, I see your example case has a destination path as the first parameter.  However, when I include a destination path, I'm told the ABI_Downloader function only uses 7, not 8, parameters.  Leaving out the destination path works, but files are then saved to my home directory.  Unfortunately, I am very limited in what I am allowed to store there, so I'd like to download the files directly to another location that I specify,

**Comment by david-e-rupp** [comment]
Problem solved. I uninstalled goespy and reinstalled from source code. The first time I installed with pip and tried --upgrade, but that didn't do it.

**Comment by palexandremello** [comment]
We need do new build to pypi, new features are only in source code. But thank so much for your feedback

**Comment by spestana** [comment]
@palexandremello let me know if I can help update pypi with the latest version of goes-py.

@david-e-rupp thanks for using the download tool! I'd also be interested in hearing about what application you're using GOES ABI imagery for.

**Comment by spestana** [comment]
I am going to close this issue, but note that we do need to release the latest version of goespy to pypi!
